---
title: "Tidy data"
output: html_document
---

```{r setup}

library(tidyverse)

```


## 'pivot_longer'

Load the PULSE data

```{r eval=FALSE}

options(tibble.print_min = 5)

pulse_data = 
  haven::read_sas("./data/public_pulse_data.sas7bdat") %>%
  janitor::clean_names()

pulse_data

```

Wide format to long format...

```{r eval=FALSE}

##Version 1

#problem with the data: the BDI score is spread across four columns which correspond to four observation times
#correct this problem using pivot_longer to condense them:

pulse_tidy_data = 
  pivot_longer(
    pulse_data, 
    bdi_score_bl:bdi_score_12m,
    names_to = "visit", 
    values_to = "bdi")

pulse_tidy_data

##Version 2

#visit is an issue- do not need to keep bdi_score_ prefix- can use additional option in pivot_longer:
pulse_tidy_data = 
  pivot_longer(
    pulse_data, 
    bdi_score_bl:bdi_score_12m,
    names_to = "visit", 
    names_prefix = "bdi_score_",
    values_to = "bdi")

pulse_tidy_data

##Version 3

#Use the code below to import, tidy, and transform the PULSE dataset into a usable format in single step:
pulse_data = 
  haven::read_sas("./data/public_pulse_data.sas7bdat") %>%
  janitor::clean_names() %>%
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit", 
    names_prefix = "bdi_score_",
    values_to = "bdi") %>%
  relocate(visit) %>%
  mutate(
    visit = replace(visit, visit == "bl", "00m"),
    visit = factor(visit, levels = str_c(c("00", "01", "06", "12"), "m"))) %>%
  arrange(id, visit)

print(pulse_data, n = 12)

```
## 'pivot_wider'

Make up some data!


```{r}

analysis_result = tibble(
  group = c("treatment","treatment","placebo","placedo"),
  time = c("pre","post","pre","post"),
  mean = c(4, 8, 3.5, 4)
)

analysis_result

#alternative- using pivot wider to show data in a non-tidy manner- inverse of pivot_longer
pivot_wider(
  analysis_result,
  names_from = "time",
  values_from = "mean")

#can use knitr::kable() to produce nicer table for reading

```

## 'Binding Rows'

First step: import each table.

```{r}

fellowship_ring = 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "B3:D6") %>%
  mutate(movie = "fellowship_ring")

two_towers = 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "F3:H6") %>%
  mutate(movie = "two_towers")

return_king = 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "J3:L6") %>%
  mutate(movie = "return_king")

```

Bind all the rows together

```{r}

lotr_tidy = 
  bind_rows(fellowship_ring, two_towers, return_king) %>%
  janitor::clean_names() %>%
  pivot_longer(
    female:male,
    names_to = "gender", 
    values_to = "words") %>%
  mutate(race = str_to_lower(race)) %>% 
  select(movie, everything()) 

lotr_tidy

```

## Joining datasets

Import and clean the FAS datasets

```{r}

pups_data =
  read_csv("./data/FAS_pups.csv", col_types = "ciiiii") %>%
  janitor::clean_names() %>%
  mutate(sex = recode(sex, '1' = "male", '2' = "female"))

litters_data =
  read_csv("./data/FAS_litters.csv", col_types = "ccddiiii") %>%
  janitor::clean_names() %>%
  separate(group, into = c("dose","day_of_tx"), sep = 3) %>%
  relocate(litter_number) %>%
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    dose = str_to_lower(dose)
  )

```

Next up, time to join them!

```{r}

fas_data = 
  left_join(pups_data, litters_data, by = "litter_number")

fas_data

```








